import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Sidebar from "@/Components/SideBar";
import Navbar from "@/Components/Navbar";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Navbar />
        <div className=" flex lg:flex-row flex-col  overflow-hidden container m-auto">
          <Sidebar />
          <main className="flex-1 overflow-auto p-4 bg-white shadow-sm">
            {children}
          </main>
        </div>
      </body>
    </html>
  );
}
